services:
  postgres:
    image: postgres:15-alpine
    container_name: em_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: em_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appeals_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appeals_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: em_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appeals_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  appeals_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
